### ISSUE TITLE
Unusable generated file

### ISSUE THREAD

**Issue by ixxeL2097** [camunda-consulting/migrate-to-camunda-tools#8]
After generating the BPMN file, the camunda modeler cannot load it properly.

My generated file is the following :
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" id="definitions_debad1f4-59c4-44fe-945c-dbdc43f39bf5" targetNamespace="http://camunda.org/examples" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <bpmndi:BPMNDiagram id="BPMNDiagram_f9544022-8681-442f-9d63-26e690a1e801">
    <bpmndi:BPMNPlane id="BPMNPlane_f1fe6725-88f3-43ff-bed2-27541f245401"/>
  </bpmndi:BPMNDiagram>
</definitions>
```

And thus, cannot load in Modeler
```
[Z:\folder\test.bpmn] no bpmnElement referenced in <bpmndi:BPMNPlane id="BPMNPlane_f1fe6725-88f3-43ff-bed2-27541f245401" /> [ warning ]
[Z:\folder\test.bpmn] no process or collaboration to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:198:14)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35390
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35413
    at new Promise (<anonymous>)
    at T (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40529
    at new Promise (<anonymous>)
    at M.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40013 [ error ]
[Z:\folder\test.bpmn] no bpmnElement referenced in <bpmndi:BPMNPlane id="BPMNPlane_f1fe6725-88f3-43ff-bed2-27541f245401" /> [ warning ]
[Z:\folder\test.bpmn] no process or collaboration to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:198:14)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35390
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35413
    at new Promise (<anonymous>)
    at T (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40529
    at new Promise (<anonymous>)
    at M.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40013 [ error ]
[Z:\folder\test.bpmn] no bpmnElement referenced in <bpmndi:BPMNPlane id="BPMNPlane_f1fe6725-88f3-43ff-bed2-27541f245401" /> [ warning ]
[Z:\folder\test.bpmn] no process or collaboration to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:198:14)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35390
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:35413
    at new Promise (<anonymous>)
    at T (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40529
    at new Promise (<anonymous>)
    at M.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Users/fred/Downloads/camunda-modeler-4.11.1-win-x64/resources/app.asar/public/3.3.js:1:40013 [ error ]
```

it looks a bit empty. Does the generation works properly ?

**Comment by superbeagle** [comment]
Sure, can you provide the original file that was fed into the converter?

**Comment by superbeagle** [comment]
If you're uncomfortable uploading it here you can send it to me at joe.pappas@camunda.com

**Comment by ixxeL2097** [comment]
sure, I sent you an email with the attached file :) thanks for your help

**Comment by ixxeL2097** [comment]
According to your explanations, I looked for the larger `xml` file extracted from the `twx` archive (the one with `BusinessProcessDiagram id="blah blah blah">` in it) and it worked like a charm. 

I have now a fully working BPMN file :)
